name: playerPenalty
version: '${project.version}'
main: akc.plugin.playerpenalty.PlayerPenaltyPlugin
api-version: 1.19
depend: [PlayerPoints, DiscordSRV]
commands:
  createIssue:
    description: "some description"
  pardon:
    description: "some description"
  broadcast:
    description: "some description"
  pay:
    description: "some description"
    command: /playerPenalty payFine
