name: PlayerPenalty
version: '${project.version}'
main: akc.plugin.playerpenalty.PlayerPenaltyPlugin
api-version: 1.19
depend: [PlayerPoints, DiscordSRV]
commands:
  createIssue:
    description: "Выписать штраф человеку"
  payFine:
    description: "Оплатить штраф"
